version: "2"
services:
  nginx_all:
    image: nginx:alpine
    container_name: nginx_all
    volumes:
      - $PWD/nginx:/etc/nginx
    ports:
      - 8080:80
    networks:
      - nginx
  web1:
    image: latelee/nginx
    container_name: web1
    volumes:
      #- $PWD/html1:/usr/local/apache2/htdocs/
      #- $PWD/html1:/usr/local/tomcat/webapps/ROOT
      - $PWD/html1:/usr/share/nginx/html
    ports:
      - 8081:80
    networks:
      - nginx

  web2:
    image: latelee/nginx
    container_name: web2
    volumes:
      #- $PWD/html2:/usr/local/apache2/htdocs/
      #- $PWD/html2:/usr/local/tomcat/webapps/ROOT
      - $PWD/html2:/usr/share/nginx/html
    ports:
      - 8082:80
    networks:
      - nginx
networks:
    nginx:
      driver: bridge
