version: '3.8'

services:
  ll-nginx:
    #image: registry.cn-shenzhen.aliyuncs.com/hxr/nginx:1.23
    image: registry.cn-shenzhen.aliyuncs.com/hxr/nginx:1.23.tb
    container_name: ll-nginx
    hostname: ll-nginx
    restart: always
    #command: "sleep 999999999999"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
      - AA=afdddddda
    ports:
      - 80:80
      - 8001:8001
      - 8002:8002
    #networks:
    #  custom:
    #    ipv4_address: 172.18.188.1

#networks:
#  custom:
#    external:
#      name: "custom-net"