# nextcloud docker-compose file
# by Late Lee<li@latelee.org>

version: '2'

#volumes:
#  nextcloud:
#  db:

services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/latelee/mysql
    container_name: nextmysql # connect sql to this name
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-net
  nextcloud:
    image: registry.cn-hangzhou.aliyuncs.com/latelee/nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 5001:80 # change 5001 as needed
    links:
      - mysql
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
